// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
  updatedAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

// Entity types
export type ProfilePreview = {
  bio: string;
  following: boolean;
  followersCount: number;
  image: string;
  username: string;
};

export type ArticlePreview = {
  author: ProfilePreview;
  createdAt: string;
  description: string;
  favorited: boolean;
  favoritesCount: number;
  slug: string;
  tagList: string[];
  title: string;
  updatedAt: string;
};

export type ArticleDetail = ArticlePreview & {
  body: string;
};

export type CommentDetail = {
  author: ProfilePreview;
  body: string;
  createdAt: string;
  id: string;
  updatedAt: string;
};

// Response types
export type UserAuth = {
  bio: string;
  email: string;
  image: string;
  token: string;
  username: string;
  role: 'admin' | 'user';
};

export type PaginationMeta = {
  total: number;
  limit: number;
  offset: number;
};

export type UserAuthResponse = {
  user: UserAuth;
};

export type ArticleDetailResponse = {
  article: ArticleDetail;
};

export type ArticlePreviewsResponse = PaginationMeta & {
  articles: ArticlePreview[];
};

export type ProfilePreviewResponse = {
  profile: ProfilePreview;
};

export type CommentDetailResponse = {
  comment: CommentDetail;
};

export type CommentDetailsResponse = PaginationMeta & {
  comments: CommentDetail[];
};

export type TagsResponse = PaginationMeta & {
  tags: string[];
};

export type ErrorResponse = {
  error: string;
};
