// let's imagine this file is autogenerated from the backend
// ideally, we want to keep these api related types in sync
// with the backend instead of manually writing them out

export type BaseEntity = {
  id: string;
  createdAt: number;
};

export type Entity<T> = {
  [K in keyof T]: T[K];
} & BaseEntity;

export type Meta = {
  page: number;
  total: number;
  totalPages: number;
};

export type User = Entity<{
  firstName: string;
  lastName: string;
  email: string;
  role: 'ADMIN' | 'USER';
  teamId: string;
  bio: string;
}>;

export type AuthResponse = {
  jwt: string;
  user: User;
};

export type Team = Entity<{
  name: string;
  description: string;
}>;

export type Discussion = Entity<{
  title: string;
  body: string;
  teamId: string;
  author: User;
}>;

export type Comment = Entity<{
  body: string;
  discussionId: string;
  author: User;
}>;

// Autogenerated types from OpenAPI schema
// Keep these in sync with the backend API specification

// Entity types
export type ProfilePreview = {
  bio: string;
  following: boolean;
  image: string;
  username: string;
};

export type ArticlePreview = {
  author: ProfilePreview;
  createdAt: string;
  description: string;
  favorited: boolean;
  favoritesCount: number;
  slug: string;
  tagList: string[];
  title: string;
  updatedAt: string;
};

export type ArticleDetail = ArticlePreview & {
  body: string;
};

export type CommentDetail = {
  author: ProfilePreview;
  body: string;
  createdAt: string;
  id: string;
  updatedAt: string;
};

// Request types
export type UserRegister = {
  email: string;

  password: string;

  username: string;
};

export type UserLogin = {
  email: string;

  password: string;
};

export type UserUpdate = {
  bio: string;

  email: string;

  image: string;

  password: string;

  username: string;
};

export type ArticleCreate = {
  body: string;

  description: string;

  tagList: string[];

  title: string;
};

export type ArticleUpdate = {
  body: string;

  description: string;

  title: string;
};

export type CommentCreate = {
  body: string;
};

// Response types
export type UserAuth = {
  bio: string;
  email: string;
  image: string;
  token: string;
  username: string;
};

export type PaginationMeta = {
  total: number;
  limit: number;
  offset: number;
};

export type UserAuthResponse = {
  user: UserAuth;
};

export type UserRegisterRequest = {
  user: UserRegister;
};

export type UserLoginRequest = {
  user: UserLogin;
};

export type UserUpdateRequest = {
  user: UserUpdate;
};

export type ArticleDetailResponse = {
  article: ArticleDetail;
};

export type ArticlePreviewsResponse = PaginationMeta & {
  articles: ArticlePreview[];
};

export type ArticleCreateRequest = {
  article: ArticleCreate;
};

export type ArticleUpdateRequest = {
  article: ArticleUpdate;
};

export type ProfilePreviewResponse = {
  profile: ProfilePreview;
};

export type CommentDetailResponse = {
  comment: CommentDetail;
};

export type CommentDetailsResponse = PaginationMeta & {
  comments: CommentDetail[];
};

export type CommentCreateRequest = {
  comment: CommentCreate;
};

export type TagsResponse = PaginationMeta & {
  tags: string[];
};

export type ErrorResponse = {
  error: string;
};
